name: Deploy Automatically

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-canary.[0-9]+'
  schedule:
    - cron: '0 9 * * *'

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  dispatch-deploy:
    runs-on: ubuntu-latest
    name: Setup Deploy
    steps:
      - name: dispatch deploy by tag
        if: ${{ github.event_name == 'push' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy.yml
          inputs: '{ "flavor": "canary" }'
      - name: dispatch deploy by schedule
        if: ${{ github.event_name == 'schedule' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy.yml
          inputs: '{ "flavor": "canary" }'
          ref: canary
