name: Languages Sync

on:
  push:
    branches: ['canary']
    paths:
      - 'packages/frontend/i18n/**'
      - '.github/workflows/languages-sync.yml'
      - '!.github/actions/setup-node/action.yml'
  pull_request_target:
    branches: ['canary']
    paths:
      - 'packages/frontend/i18n/**'
      - '.github/workflows/languages-sync.yml'
      - '!.github/actions/setup-node/action.yml'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Check Language Key
        if: github.ref != 'refs/heads/canary'
        run: yarn workspace @affine/i18n run sync-languages:check
        env:
          TOLGEE_API_KEY: ${{ secrets.TOLGEE_API_KEY }}

      - name: Sync Languages
        if: github.ref == 'refs/heads/canary'
        run: yarn workspace @affine/i18n run sync-languages
        env:
          TOLGEE_API_KEY: ${{ secrets.TOLGEE_API_KEY }}
