{{- if .Values.app.captcha.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.app.captcha.secretName }}"
type: Opaque
data:
  turnstileSecret: {{ .Values.app.captcha.turnstile.secret | b64enc }}
{{- end }}
