{{- if .Values.app.copilot.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.app.copilot.secretName }}"
type: Opaque
data:
  openaiSecret: {{ .Values.app.copilot.openai.key | b64enc }}
  falSecret: {{ .Values.app.copilot.fal.key | b64enc }}
  unsplashSecret: {{ .Values.app.copilot.unsplash.key | b64enc }}
{{- end }}
