{{- if .Values.app.metrics.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.app.metrics.secretName }}"
type: Opaque
data:
  customerIoSecret: {{ .Values.app.metrics.customerIo.token | b64enc }}
{{- end }}
