{{- if .Values.app.oauth.google.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.app.oauth.google.secretName }}"
type: Opaque
data:
  clientId: "{{ .Values.app.oauth.google.clientId | b64enc }}"
  clientSecret: "{{ .Values.app.oauth.google.clientSecret | b64enc }}"
{{- end }}
---
{{- if .Values.app.oauth.github.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.app.oauth.github.secretName }}"
type: Opaque
data:
  clientId: "{{ .Values.app.oauth.github.clientId | b64enc }}"
  clientSecret: "{{ .Values.app.oauth.github.clientSecret | b64enc }}"
{{- end }}
