{{- if .Values.app.objectStorage.r2.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.app.objectStorage.r2.secretName }}"
type: Opaque
data:
  accountId: {{ .Values.app.objectStorage.r2.accountId | b64enc }}
  accessKeyId: {{ .Values.app.objectStorage.r2.accessKeyId | b64enc }}
  secretAccessKey: {{ .Values.app.objectStorage.r2.secretAccessKey | b64enc }}
{{- end }}
